<style type="text/css">
  .error{
    color:red !important;
  }
</style>
<?php 
$customer_user_id = $this->session->user_id;
$profile = $this->user->profile_details(); ?>
<?php
if($this->session->flashdata('success')){
   echo '<div class="alert alert-info">'.$this->session->flashdata('success').'</div>';
}
?>
<div class="cls_main_top">
  <div class="cls_mid_con cls_comm_bg">
    <div class="container">
      <div class="row">
        <?php $this->load->view('user/v_aboutsidebar'); ?>
        <div class="col-md-9 col-sm-8">
          <div class="cls_comm_head"> 2 Factor Authentification </div>
          <?php  
          if($user_details=="disable" || $user_details==""){ ?>
          <div class="cls_facr_box">
            <h4>Enter your secret code into the Google Authenticator App on your phone or tablet.</h4>
            <h3><?php echo $secret_code; ?></h3>
            <div align="center"> <p><img src="<?php echo $url; ?>" alt=""></p></div>
            <h3 class="mar-top-30">Now get the code generated from your app!</h3>
            <h4>To activate 2-Step Verification please entre the code generated by your Google Authenticator App.</h4>
            <form class="form-horizontal" name="activate_form" id="activate_form" method="post">
              <div class="form-group">
                <label for="inputEmail3" class="col-sm-3 control-label">Secret Code</label>
                <div class="col-sm-5">
                 <input type="text" class="form-control" id="secret_code" name="secret_code" style="cursor:disabled;" placeholder="" value="<?php echo $secret_code; ?>" readonly> 
               </div>
             </div>
             <div class="form-group">
              <label for="inputPassword3" class="col-sm-3 control-label">Enter Code </label>
              <div class="col-sm-5">
                <input type="text" class="form-control" id="one_code" name="one_code" placeholder=""> 
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-3 col-sm-10">
               <button type="submit" class="cls_dow_btn" id="enable_tfa">ACTIVATE NOW  </button> 
             </div>
           </div>
         </form>
       </div>
       <?php } ?>
       <?php if($user_details=="enable"){ ?>
       <div class="cls_facr_box">
         <p><strong>Your TFA code Activated</strong> if you deactivate please Click the below button...</p>
         <div align="center"> <a href="#"><p><img src="<?php echo $url; ?>" alt=""></p></a></div>
         <button type="button" class="cls_dow_btn"  onclick="tfa()" id="active_tfa" name="active_tfa" onclick="show_tfa()"> DEACTIVATE TFA </button>
       </div>
       <?php } ?>
       <span id="tfa_error" class="alert alert-info" style="display:none;float: left; margin: -51px 0 0;"></span>
     </div>
   </div> 
 </div> 
 <br>
 <br>
</div>
</div>